riot_api_key: "<your-api-key>"
team:
  name: "<your-team-name>"
  members: 
  - "<member-1-puuid>"
  - "<member-2-puuid>"
  ...
  - "<member-n-puuid>"

params:
  match:
    - "gameStartTimestamp"
    - "gameDuration"
    - "platform"
    - "creation"
    - "mode"
    - "gameCreation"
    - "gameEndTimestamp"
    - "duration"
    - "continent"
    - "id"
    - "start"
    - "type"
    - "tournamentCode"
    - "mapId"
    - "privateGame"
    - "queue"
    - "version"
    - "name"
    - "matchId"
  stats:
    - "physicalDamageDealt"
    - "visionScore"
    - "goldSpent"
    - "goldEarned"
    - "totalHeal"
    - "item3"
    - "trueDamageDealt"
    - "inhibitorKills"
    - "champLevel"
    - "damageDealtToTurrets"
    - "visionWardsBoughtInGame"
    - "detectorWardsPlaced"
    - "consumablesPurchased"
    - "killingSprees"
    - "totalMinionsKilled"
    - "spell1Casts"
    - "objectivesStolenAssists"
    - "spell4Casts"
    - "physicalDamageTaken"
    - "magicDamageDealt"
    - "damageDealtToObjectives"
    - "item4"
    - "item5"
    - "pentaKills"
    - "largestKillingSpree"
    - "bountyLevel"
    - "firstTowerKill"
    - "champExperience"
    - "firstBloodAssist"
    - "item6"
    - "spell3Casts"
    - "longestTimeSpentLiving"
    - "damageDealtToBuildings"
    - "tripleKills"
    - "turretKills"
    - "dragonKills"
    - "firstTowerAssist"
    - "wardsPlaced"
    - "nexusLost"
    - "sightWardsBoughtInGame"
    - "timeCCingOthers"
    - "turretTakedowns"
    - "wardsKilled"
    - "item2"
    - "baronKills"
    - "trueDamageTaken"
    - "deaths"
    - "totalDamageTaken"
    - "objectivesStolen"
    - "totalHealsOnTeammates"
    - "totalDamageDealt"
    - "timePlayed"
    - "totalTimeSpentDead"
    - "firstBloodKill"
    - "unrealKills"
    - "inhibitorsLost"
    - "itemsPurchased"
    - "physicalDamageDealtToChampions"
    - "magicDamageTaken"
    - "damageSelfMitigated"
    - "spell2Casts"
    - "largestMultiKill"
    - "totalUnitsHealed"
    - "item0"
    - "assists"
    - "nexusKills"
    - "kills"
    - "totalDamageShieldedOnTeammates"
    - "summoner2Casts"
    - "championTransform"
    - "summoner1Casts"
    - "totalDamageDealtToChampions"
    - "neutralMinionsKilled"
    - "item1"
    - "trueDamageDealtToChampions"
    - "quadraKills"
    - "magicDamageDealtToChampions"
    - "totalTimeCCDealt"
    - "doubleKills"
    - "turretsLost"
    - "inhibitorTakedowns"
    - "nexusTakedowns"
    - "largestCriticalStrike"
