development: false

team:
  name: "<your-team-name>" &team_name
  members:
    1: "<player-1-name>"
    2: "<player-2-name>"
    ...
    <n>: - "<player-n-name>"

logging:
  configuration_file: "logging.config.yaml"

database:
  driver: 
    # - local
    # - mongodb
    # - gsheets
    - memory
  mongodb:
    uri: "<your-mongodb-uri>"
    database: "pylol"
    collection: "data"
  local:
    output_file: "stats.json"
  gsheets:
    credentials_path: "creds.json"
    spreadsheet_id: "<a_spreadsheet_id>"

discord:
  api_key: "<your-api-key>"
  prefix: '!'
  intents: 
    - "guilds"
    - "members"
    - "moderation"
    - "bans"
    - "emojis"
    - "emojis_and_stickers"
    - "integrations"
    - "webhooks"
    - "invites"
    - "voice_states"
    - "presences"
    - "messages"
    - "guild_messages"
    - "dm_messages"
    - "reactions"
    - "guild_reactions"
    - "dm_reactions"
    - "typing"
    - "guild_typing"
    - "dm_typing"
    - "message_content"
    - "guild_scheduled_events"
    - "auto_moderation"
    - "auto_moderation_configuration"
    - "auto_moderation_execution"
  team:
    users:
      1: <user-1-discord-id>
      2: <user-2-discord-id>
      ...
      <n>: <user-n-discord-id>
  embed:
    footer: *team_name
    primary_color: 0xFFFFFF
    secondary_color: 0xDBDBDB
    error_color: 0xFF0000

riot:
  api_key: "<your-api-key>"
  team:
    members: 
    - "<member-1-riot-id>"
    - "<member-2-riot-puuid>"
    ...
    - "<member-n-riot-puuid>"
  params:
    match:
      - "mode"
      - "duration"
      - "start"
      - "type"
      - "tournamentCode"
      - "mapId"
      - "privateGame"
      - "queue"
      - "matchId"
    stats:
      - "physicalDamageDealt"
      - "visionScore"
      - "goldSpent"
      - "goldEarned"
      - "totalHeal"
      - "item3"
      - "trueDamageDealt"
      - "inhibitorKills"
      - "champLevel"
      - "damageDealtToTurrets"
      - "visionWardsBoughtInGame"
      - "detectorWardsPlaced"
      - "consumablesPurchased"
      - "killingSprees"
      - "totalMinionsKilled"
      - "spell1Casts"
      - "objectivesStolenAssists"
      - "spell4Casts"
      - "physicalDamageTaken"
      - "magicDamageDealt"
      - "damageDealtToObjectives"
      - "item4"
      - "item5"
      - "pentaKills"
      - "largestKillingSpree"
      - "bountyLevel"
      - "firstTowerKill"
      - "champExperience"
      - "firstBloodAssist"
      - "item6"
      - "spell3Casts"
      - "longestTimeSpentLiving"
      - "damageDealtToBuildings"
      - "tripleKills"
      - "turretKills"
      - "dragonKills"
      - "firstTowerAssist"
      - "wardsPlaced"
      - "nexusLost"
      - "sightWardsBoughtInGame"
      - "timeCCingOthers"
      - "turretTakedowns"
      - "wardsKilled"
      - "item2"
      - "baronKills"
      - "trueDamageTaken"
      - "deaths"
      - "totalDamageTaken"
      - "objectivesStolen"
      - "totalHealsOnTeammates"
      - "totalDamageDealt"
      - "timePlayed"
      - "totalTimeSpentDead"
      - "firstBloodKill"
      - "unrealKills"
      - "inhibitorsLost"
      - "itemsPurchased"
      - "physicalDamageDealtToChampions"
      - "magicDamageTaken"
      - "damageSelfMitigated"
      - "spell2Casts"
      - "largestMultiKill"
      - "totalUnitsHealed"
      - "item0"
      - "assists"
      - "nexusKills"
      - "kills"
      - "totalDamageShieldedOnTeammates"
      - "summoner2Casts"
      - "championTransform"
      - "summoner1Casts"
      - "totalDamageDealtToChampions"
      - "neutralMinionsKilled"
      - "item1"
      - "trueDamageDealtToChampions"
      - "quadraKills"
      - "magicDamageDealtToChampions"
      - "totalTimeCCDealt"
      - "doubleKills"
      - "turretsLost"
      - "inhibitorTakedowns"
      - "nexusTakedowns"
      - "largestCriticalStrike"
